# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_toeplitz_rcpp_hello_world', PACKAGE = 'toeplitz')
}

#' An RcppArmadillo function to compute the
#' determinant of a Toeplitz matrix
#'
#' @param c A numeric vector, which is the first row of the Toeplitz matrix
#' @return A list containing the log determinant and two vectors z and v
#' to be passed to trenchInv to calculate the inverse.
trenchDetcpp <- function(c) {
    .Call('_toeplitz_trenchDetcpp', PACKAGE = 'toeplitz', c)
}

#' An RcppArmadillo function to compute the
#' inverse of a Toeplitz matrix
#'
#' @param v A numeric vector, which is calculated from trenchDetcpp
#' @return The inverse of the toeplitz matrix
trenchInvcpp <- function(v) {
    .Call('_toeplitz_trenchInvcpp', PACKAGE = 'toeplitz', v)
}

