// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _toeplitz_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// trenchDetcpp
List trenchDetcpp(arma::vec c);
RcppExport SEXP _toeplitz_trenchDetcpp(SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(trenchDetcpp(c));
    return rcpp_result_gen;
END_RCPP
}
// trenchInvcpp
arma::mat trenchInvcpp(arma::vec v);
RcppExport SEXP _toeplitz_trenchInvcpp(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(trenchInvcpp(v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_toeplitz_rcpp_hello_world", (DL_FUNC) &_toeplitz_rcpp_hello_world, 0},
    {"_toeplitz_trenchDetcpp", (DL_FUNC) &_toeplitz_trenchDetcpp, 1},
    {"_toeplitz_trenchInvcpp", (DL_FUNC) &_toeplitz_trenchInvcpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_toeplitz(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
